sequenceDiagram
    autonumber
    participant Vendor
    participant GitHub_Repository as GitHub Repository
    participant GitHub_Actions as GitHub Actions
    participant Merkle_Proof_Service as Merkle Proof Service
    participant Proof_Orchestrator_Service as Proof Orchestrator Service

    Vendor->>GitHub_Repository: git push
    GitHub_Repository->>GitHub_Actions: Trigger workflow
    note right of GitHub_Actions: Compute SBOM

    GitHub_Actions->>Merkle_Proof_Service: Build SMT from SBOM
    activate Merkle_Proof_Service
    Merkle_Proof_Service-->>GitHub_Actions: Return Root Hash
    deactivate Merkle_Proof_Service

    GitHub_Actions->>Proof_Orchestrator_Service: Generate Proof (root_hash, banned_list)
    activate Proof_Orchestrator_Service
    note right of Proof_Orchestrator_Service: Orchestrates proof generation, storage, and blockchain registration
    Proof_Orchestrator_Service-->>GitHub_Actions: Response (ipfs_cid, tx_hash, compliance_status)
    deactivate Proof_Orchestrator_Service

    note right of GitHub_Actions: Generate and sign build attestation (using OIDC token)