sequenceDiagram
    autonumber

    participant Vendor
    participant GitHub_Repository as GitHub Repository
    participant GitHub_Actions as GitHub Actions
    participant CVE_Database as CVE Database
    participant Proving_Service as Proving Service
    participant IPFS_Service as IPFS Service
    participant Blockchain as Blockchain (Smart Contract)

    Vendor->>GitHub_Repository: 1. git push
    GitHub_Repository->>GitHub_Actions: 2. Trigger workflow

    note right of GitHub_Actions: 3. Compute Software Digest, SBOM, H(SBOM)
    
    GitHub_Actions->>CVE_Database: 4. Request CVE dataset with SBOM
    CVE_Database-->>GitHub_Actions: 5. Send CVE dataset

    note right of GitHub_Actions: 6. Compute H(CVE dataset)

    GitHub_Actions->>Proving_Service: 7. Prove request (SBOM, H(SBOM), CVE dataset, H(CVE dataset))
    activate Proving_Service
    note right of Proving_Service: Verify hashes, generate ZK proof
    Proving_Service-->>GitHub_Actions: 8. Response (proof, imageId, isValid)
    deactivate Proving_Service

    GitHub_Actions->>IPFS_Service: 9. Store request (H(SBOM), proof)
    activate IPFS_Service
    note right of IPFS_Service: Store bundle
    IPFS_Service-->>GitHub_Actions: 11. Send ipfsCid
    deactivate IPFS_Service

    GitHub_Actions->>Blockchain: 12. Store metadata transaction (Software Digest, H(SBOM), H(CVE dataset), ipfsCid, Timestamp, Runner ID etc.)
    activate Blockchain
    note right of Blockchain: Confirm transaction
    Blockchain-->>GitHub_Actions: 13. Transaction receipt
    deactivate Blockchain
    note right of GitHub_Actions: 13. Generate & sign build attestation (using OIDC token)
